name: Build KernelSU Next
on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true
        default: 'sm7675'
      FEIL:
        description: "配置文件"
        required: true
        default: 'oneplus_ace_3v_v'
      CPUD:
        description: "处理器代号"
        required: true
        default: 'pineapple'

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
     - name: Check Out
       uses: actions/checkout@v3
       
     - name: Configure Git
       run: |
        git config --global user.name "wuua"
        git config --global user.email "3436678798@qq.com"

     - name: Clean up disk space
       run: |
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet /etc/mysql /var/lib/mysql
        sudo rm -rf /usr/local/lib/android
        df -h
        
     - name: Install dependencies
       run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y python3 git curl

     - name: Install repo tool
       run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod a+x ~/repo
        sudo mv ~/repo /usr/local/bin/repo

     - name: Initialize repo and sync
       run: |
        mkdir kernel_workspace && cd kernel_workspace
        repo init -u https://github.com/gbxx1145/Action-KernelSU.git -b refs/heads/oneplus/${{ github.event.inputs.CPU }} -m ${{ github.event.inputs.FEIL }}.xml --depth=1
        repo sync
        rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
        sed -i 's/ -dirty//g' kernel_platform/msm-kernel/scripts/setlocalversion

     - name: Enable lxc & docker config
       run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        wget https://github.com/jqtmviyu/LXC_KernelSU_Action/raw/refs/heads/main/patches/lxc-docker-config.conf
        cat lxc-docker-config.conf >> kernel_platform/msm-kernel/arch/arm64/configs/gki_defconfig
        echo "# CONFIG_ANDROID_PARANOID_NETWORK is not set" >> kernel_platform/msm-kernel/arch/arm64/configs/gki_defconfig
        
     - name: Build kernel
       run: |
        cd kernel_workspace
        ./kernel_platform/oplus/build/oplus_build_kernel.sh ${{ github.event.inputs.CPUD }} gki

     - name: Make AnyKernel3
       run: |
        git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
        rm -rf ./AnyKernel3/.git
        cp kernel_workspace/kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-gki/dist/Image ./AnyKernel3/

     - name: Upload AnyKernel3
       uses: actions/upload-artifact@v4
       with:
        name: AnyKernel3_KernelSU_Next_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}
        path: ./AnyKernel3/*

     - name: Upload boot.img
       uses: actions/upload-artifact@v4
       with:
        name: boot_KernelSU_Next_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}
        path: kernel_workspace/kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-gki/dist/boot.img

